FROM node:22.11

RUN apt-get update && apt-get install -y netcat-openbsd

WORKDIR /usr/src/app

COPY package.json package-lock.json ./

RUN npm install

COPY src ./src
COPY tsconfig.json ./
COPY .env.local ./.env
COPY wait-for-it.sh ./

RUN chmod +x ./wait-for-it.sh

CMD ["bash", "-c", "./wait-for-it.sh postgres ${DB_PORT} 60 && npm run start:dev"]
